return {
  "catppuccin/nvim",
  enabled = true,
  name = "catppuccin",
  config = function()
    require("catppuccin").setup {
      flavour = "mocha", -- mocha, macchiato, frappe, latte
      compile = {
        enabled = true,
        path = vim.fn.stdpath "cache" .. "/catppuccin",
      },
      color_overrides = {
        -- frappe = {
        --   rosewater = "#eb7a73",
        --   flamingo = "#eb7a73",
        --   red = "#eb7a73",
        --   maroon = "#eb7a73",
        --   pink = "#e396a4",
        --   mauve = "#e396a4",
        --   peach = "#e89a5e",
        --   yellow = "#E7B84C",
        --   green = "#7cb66a",
        --   teal = "#99c792",
        --   sky = "#99c792",
        --   sapphire = "#99c792",
        --   blue = "#8dbba3",
        --   lavender = "#8dbba3",
        --   text = "#f1e4c2",
        --   subtext1 = "#e5d5b1",
        --   subtext0 = "#c5bda3",
        --   overlay2 = "#b8a994",
        --   overlay1 = "#a39284",
        --   overlay0 = "#656565",
        --   surface2 = "#5d5d5d",
        --   surface1 = "#505050",
        --   surface0 = "#393939",
        --   base = "#1d2224",
        --   mantle = "#1d2224",
        --   crust = "#1f2223",
        -- },
        macchiato = { -- everforest
          rosewater = "#eb7a73",
          flamingo = "#eb7a73",
          red = "#eb7a73",
          maroon = "#eb7a73",
          pink = "#e396a4",
          mauve = "#e396a4",
          peach = "#e89a5e",
          yellow = "#e8b267",
          green = "#b9c675",
          teal = "#99c792",
          sky = "#99c792",
          sapphire = "#99c792",
          blue = "#8dbba3",
          lavender = "#8dbba3",
          text = "#f1e4c2",
          subtext1 = "#e5d5b1",
          subtext0 = "#c5bda3",
          overlay2 = "#b8a994",
          overlay1 = "#a39284",
          overlay0 = "#656565",
          surface2 = "#5d5d5d",
          surface1 = "#505050",
          surface0 = "#393939",
          base = "#2e3233",
          mantle = "#242727",
        },
        -- macchiato = {
        --   rosewater = "#F5B8AB",
        --   flamingo = "#F29D9D",
        --   pink = "#AD6FF7",
        --   mauve = "#FF8F40",
        --   red = "#E66767",
        --   maroon = "#EB788B",
        --   peach = "#FAB770",
        --   yellow = "#FACA64",
        --   green = "#70CF67",
        --   teal = "#4CD4BD",
        --   sky = "#61BDFF",
        --   sapphire = "#4BA8FA",
        --   blue = "#00BFFF",
        --   lavender = "#00BBCC",
        --   text = "#C1C9E6",
        --   subtext1 = "#A3AAC2",
        --   subtext0 = "#8E94AB",
        --   overlay2 = "#7D8296",
        --   overlay1 = "#676B80",
        --   overlay0 = "#464957",
        --   surface2 = "#3A3D4A",
        --   surface1 = "#2F313D",
        --   surface0 = "#1D1E29",
        --   base = "#0b0b12",
        --   mantle = "#11111a",
        --   crust = "#191926",
        -- },
        -- mocha = { -- gruvbox material
        --   rosewater = "#ea6962",
        --   flamingo = "#ea6962",
        --   red = "#ea6962",
        --   maroon = "#ea6962",
        --   pink = "#d3869b",
        --   mauve = "#d3869b",
        --   peach = "#e78a4e",
        --   yellow = "#d8a657",
        --   green = "#a9b665",
        --   teal = "#89b482",
        --   sky = "#89b482",
        --   sapphire = "#89b482",
        --   blue = "#7daea3",
        --   lavender = "#7daea3",
        --   text = "#ebdbb2",
        --   subtext1 = "#d5c4a1",
        --   subtext0 = "#bdae93",
        --   overlay2 = "#a89984",
        --   overlay1 = "#928374",
        --   overlay0 = "#595959",
        --   surface2 = "#4d4d4d",
        --   surface1 = "#404040",
        --   surface0 = "#292929",
        --   base = "#1d2021",
        --   mantle = "#191b1c",
        --   crust = "#141617",
        -- },
        mocha = { -- high contrast
          rosewater = "#efc9c2",
          flamingo = "#ebb2b2",
          pink = "#f2a7de",
          mauve = "#b889f4",
          red = "#ea7183",
          maroon = "#ea838c",
          peach = "#f39967",
          yellow = "#eaca89",
          green = "#96d382",
          teal = "#78cec1",
          sky = "#91d7e3",
          sapphire = "#68bae0",
          blue = "#739df2",
          lavender = "#a0a8f6",
          text = "#b5c1f1",
          subtext1 = "#a6b0d8",
          subtext0 = "#959ec2",
          overlay2 = "#848cad",
          overlay1 = "#717997",
          overlay0 = "#63677f",
          surface2 = "#505469",
          surface1 = "#3e4255",
          surface0 = "#2c2f40",
          base = "#1a1c2a",
          mantle = "#141620",
          crust = "#0e0f16",
        },
      },
      custom_highlights = function(colors)
        return {

          -- General
          MatchParen = { fg = colors.yellow, style = { "bold" } },
          FloatBorder = { fg = colors.surface0, bg = "NONE" }, -- TODO: this seems to not be working
          WinSeparator = { fg = colors.surface2 },
          OverLength = { fg = colors.red, bg = colors.base },
          HighlightedyankRegion = {
            reverse = true,
          },

          -- TScontext
          TreesitterContextBottom = {
            sp = colors.surface0, -- INFO: don't know about this
            style = { "bold", "italic" },
          },

          -- noice
          NoiceCmdlinePopupBorder = { fg = colors.overlay2, bg = "NONE" },
          NoiceCmdlinePopupTitle = { fg = colors.subtext0 },
          -- navic
          NavicText = { fg = colors.subtext1 },
          NavicSeparator = { fg = colors.overlay0 },
          -- cmp
          CmpSel = { fg = colors.base, bg = colors.green },
          CmpItemMenu = { fg = colors.mauve, bg = "NONE" },
          -- CmpBorder = { fg = colors.surface1, bg = "NONE" },
          CmpItemKindSnippet = { fg = colors.base, bg = colors.mauve },
          CmpItemKindKeyword = { fg = colors.base, bg = colors.red },
          CmpItemKindText = { fg = colors.base, bg = colors.teal },
          CmpItemKindMethod = { fg = colors.base, bg = colors.blue },
          CmpItemKindConstructor = { fg = colors.base, bg = colors.blue },
          CmpItemKindFunction = { fg = colors.base, bg = colors.blue },
          CmpItemKindFolder = { fg = colors.base, bg = colors.blue },
          CmpItemKindModule = { fg = colors.base, bg = colors.blue },
          CmpItemKindConstant = { fg = colors.base, bg = colors.peach },
          CmpItemKindField = { fg = colors.base, bg = colors.green },
          CmpItemKindProperty = { fg = colors.base, bg = colors.green },
          CmpItemKindEnum = { fg = colors.base, bg = colors.green },
          CmpItemKindUnit = { fg = colors.base, bg = colors.green },
          CmpItemKindClass = { fg = colors.base, bg = colors.yellow },
          CmpItemKindVariable = { fg = colors.base, bg = colors.flamingo },
          CmpItemKindFile = { fg = colors.base, bg = colors.blue },
          CmpItemKindInterface = { fg = colors.base, bg = colors.yellow },
          CmpItemKindColor = { fg = colors.base, bg = colors.red },
          CmpItemKindReference = { fg = colors.base, bg = colors.red },
          CmpItemKindEnumMember = { fg = colors.base, bg = colors.red },
          CmpItemKindStruct = { fg = colors.base, bg = colors.blue },
          CmpItemKindValue = { fg = colors.base, bg = colors.peach },
          CmpItemKindEvent = { fg = colors.base, bg = colors.blue },
          CmpItemKindOperator = { fg = colors.base, bg = colors.blue },
          CmpItemKindTypeParameter = { fg = colors.base, bg = colors.blue },
          CmpItemKindCopilot = { fg = colors.base, bg = colors.teal },

          NeotestPassed = { fg = colors.green },
          NeotestFailed = { fg = colors.red },
          NeotestRunning = { fg = colors.yellow },
          NeotestSkipped = { fg = colors.blue },
          NeotestFile = { fg = colors.peach },
          NeotestNamespace = { fg = colors.peach },
          NeotestDir = { fg = colors.peach },
          NeotestFocused = { fg = colors.mauve, bold = true, underline = true },
          NeotestAdapterName = { fg = colors.red },
          NeotestIndent = { fg = colors.yellow },
          NeotestExpandMarker = { fg = colors.yellow },
          NeotestWinSelect = { fg = colors.yellow, bold = true },
          NeotestTest = { fg = colors.subtext2 },
        }
      end,
      show_end_of_buffer = false,
      term_colors = true,
      styles = {
        comments = { "italic" },
        strings = { "italic" },
      },
      integrations = {
        gitsigns = true,
        notify = true,
        noice = true,
        neogit = true,
        dashboard = true,
        diffview = true,
        ufo = true,
        telescope = { enabled = true, style = "nvchad" },
        which_key = true,
        colorful_winsep = true,
        treesitter = true,
        fidget = true,
        cmp = true,
        flash = true,
        treesitter_context = true,
        mason = true,
        harpoon = true,
        lsp_trouble = true,
        navic = {
          enabled = true,
          custom_bg = "NONE",
        },
        dap = {
          enabled = true,
          enable_ui = true,
        },
        native_lsp = {
          enabled = true,
          inlay_hints = {
            background = false,
          },
          virtual_text = {
            errors = { "italic" },
            hints = { "italic" },
            warnings = { "italic" },
            information = { "italic" },
          },
          mini = {
            enabled = true,
          },
          underlines = {
            errors = { "undercurl" },
            hints = { "underline" },
            warnings = { "underline" },
            information = { "underline" },
          },
        },
      },
    }

    vim.cmd [[colorscheme catppuccin]]
    vim.cmd.highlight "DiagnosticUnderlineError gui=undercurl" -- use undercurl for error, if supported by terminal
  end,
  build = ":CatppuccinCompile",
  priority = 1000,
}
